### ISSUE TITLE
ocpmodels unavailable?

### ISSUE THREAD

**Issue by njszym** [ulissigroup/charge-density-models#19]
In the README file for this repository, it points to [FAIR-Chem](https://github.com/FAIR-Chem/fairchem) for the installation of ocpmodels. However, that package does not seem to exist in the FAIR-Chem repository. Is this deprecated, and if so, is there a replacement for ocpmodels that could be used to run the charge density prediction models?

**Comment by emsunshine** [comment]
Hello, you are correct that the repository has been renamed to FAIR-chem. The `ocpmodels` package can now be found at `fairchem.core`. I will update this repository accordingly

**Comment by arupmondal835** [comment]
Hello,
I am having the same issue. I have successfully installed the fairchem.core package through pip. But still getting the ocpmodels error. 
ModuleNotFoundError: No module named 'ocpmodels'
Could you help me with some detailed guidance?
Thank you,

**Comment by arupmondal835** [comment]
After some exploration I realized ocpmodels should be replaced with fairchem.core in the code. Is that right? Also, I am not able to find the base model from the base.py. Should it be renamed as well?

Traceback (most recent call last):
  File "/kfs2/projects/gt47/amondal2/property_charge_density-models/x.py", line 22, in <module>
    import cdm.models
  File "/kfs2/projects/gt47/amondal2/property_charge_density-models/cdm/__init__.py", line 1, in <module>
    from .models import *
  File "/kfs2/projects/gt47/amondal2/property_charge_density-models/cdm/models/__init__.py", line 2, in <module>
    from .gemnet_charge import GemNetT_charge
  File "/kfs2/projects/gt47/amondal2/property_charge_density-models/cdm/models/gemnet_charge.py", line 21, in <module>
    from fairchem.core.models.base import BaseModel
ImportError: cannot import name 'BaseModel' from 'fairchem.core.models.base' (/projects/gt47/amondal2/Source/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/fairchem/core/models/base.py)

**Comment by emsunshine** [comment]
You can probably get rid of the BaseModel import in gemnet_charge.py. I don't think it's actually used in the file.

If you manage to get the repository working with the current fairchem repository feel free to submit a PR!

**Comment by arupmondal835** [comment]
Thanks! Yes, that's what I did. However there are several other attributes that the code is importing but fairchem does not have them. such as:

  _Jd = torch.load(os.path.join(os.path.dirname(__file__), "Jd.pt"))
Traceback (most recent call last):
  File "/kfs2/projects/gt47/amondal2/property_charge_density-models/x.py", line 23, in <module>
    import cdm.models
  File "/kfs2/projects/gt47/amondal2/property_charge_density-models/cdm/__init__.py", line 2, in <module>
    from .charge_trainer import ChargeTrainer
  File "/kfs2/projects/gt47/amondal2/property_charge_density-models/cdm/charge_trainer.py", line 21, in <module>
    from fairchem.core.common.data_parallel import (
ImportError: cannot import name 'OCPDataParallel' from 'fairchem.core.common.data_parallel' (/projects/gt47/amondal2/Source/colabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/fairchem/core/common/data_parallel.py)

I think I can not get rid of OCPDataParallel as this is being used in the code. Do you know how to fix it?

Thanks

**Comment by emsunshine** [comment]
I guess torch's DistributedDataParallel might work, following the changes that were made here: https://github.com/FAIR-Chem/fairchem/blob/e11e78e87f791241b3759a7218a1b0e307a49662/src/fairchem/core/trainers/base_trainer.py#L578
